### ISSUE TITLE
Integrate HTML Prettifier

### ISSUE THREAD

**Issue by Vampurica** [ItzDerock/discord-html-transcripts#150]
For a potential enhancement, integrate html-prettify or equivalent to make the output source easily legible.

**Comment by ItzDerock** [comment]
I think this may be something out of the scope of the package as you can specify the output type to be a string and pretty-ify it yourself. In older versions this was an option since we used JSDOM and JSDOM didn't automatically minify the output, but since we are using react now, the output is already minified. 

Maybe we should convert this issue to a discussion, and if people can upvote if they think this would be a good addition.
